/** Icon map of jobs to their fontawesome5 (free) counterpart. */
export const JOB2ICON = {
  'IA': 'eye',
  'Assistant': 'toolbox',
  'Technicien atmosphérique': 'fan',
  'Barman': 'cocktail',
  'Botaniste': 'seedling',
  'Capitaine': 'crown',
  'Technicien cargo': 'box',
  'Commandant de CentCom': 'star',
  'CentCom Head Intern': 'pen-fancy',
  'CentCom Intern': 'pen-alt',
  'CentCom Official': 'medal',
  'Chapelain': 'cross',
  'Chef cuistot': 'utensils',
  'Chimiste': 'prescription-bottle',
  'Chef ingénieur': 'user-astronaut',
  'Chef médecin': 'user-md',
  'Clown': 'face-grin-tears',
  'Cook': 'utensils',
  'Conservateur': 'book',
  'Cyborg': 'robot',
  'Détective': 'user-secret',
  'Généticien': 'dna',
  'Chef du personnel': 'dog',
  'Chef de la sécurité': 'user-shield',
  'Concierge': 'soap',
  'Avocat': 'gavel',
  'Médecin généraliste': 'staff-snake',
  'Mime': 'comment-slash',
  'Urgentiste': 'truck-medical',
  'IA personnelle': 'mobile-alt',
  'Prisonnier': 'lock',
  'Psychiatre': 'brain',
  'Contre-maître': 'sack-dollar',
  'Directeur des recherches': 'user-graduate',
  'Roboticien': 'battery-half',
  'Scientifique': 'flask',
  'Officier de sécurité (Cargo)': 'shield-halved',
  'Officier de sécurité (Ingénierie)': 'shield-halved',
  'Officier de sécurité (Médical)': 'shield-halved',
  'Security Officer (Science)': 'shield-halved',
  'Officier de sécurité': 'shield-halved',
  'Mineur': 'digging',
  'Ingénieur technique': 'gears',
  'Syndicate Operative': 'dragon',
  'Virologue': 'virus',
  'Gardien': 'handcuffs',
} as const;

export type AvailableJob = keyof typeof JOB2ICON;
