/obj/item/food/bait
	name = "Ceci est un appât"
	desc = "Vous avez été attrapé."
	icon = 'icons/obj/fishing.dmi'
	/// Quality trait of this bait
	var/bait_quality = BASIC_QUALITY_BAIT_TRAIT
	/// Icon state added to main fishing rod icon when this bait is equipped
	var/rod_overlay_icon_state

/obj/item/food/bait/Initialize(mapload)
	. = ..()
	ADD_TRAIT(src, bait_quality, INNATE_TRAIT)

/obj/item/food/bait/worm
	name = "Ver"
	desc = "Un ver qui se trémouse, il vient d'une boîte d'appâts pour la pêche. Vous n'allez pas le manger, n'est-ce pas ?"
	icon = 'icons/obj/fishing.dmi'
	icon_state = "worm"
	food_reagents = list(/datum/reagent/consumable/nutriment/protein = 1)
	tastes = list("de viande" = 1, "de vers" = 1)
	foodtypes = GROSS | MEAT | BUGS
	w_class = WEIGHT_CLASS_TINY
	bait_quality = BASIC_QUALITY_BAIT_TRAIT
	rod_overlay_icon_state = "worm_overlay"

/obj/item/food/bait/worm/premium
	name = "Ver super gluant"
	desc = "Ce ver a l'air très sophistiqué."
	bait_quality = GOOD_QUALITY_BAIT_TRAIT

/obj/item/food/bait/natural
	name = "Appât naturel"
	desc = "Les poissons n'arrêteront jamais d'en manger !"
	icon = 'icons/obj/medical/chemical.dmi'
	icon_state = "pill9"
	lefthand_file = 'icons/mob/inhands/items_lefthand.dmi'
	righthand_file = 'icons/mob/inhands/items_righthand.dmi'
	inhand_icon_state = "pen"
	food_reagents = list(/datum/reagent/drug/kronkaine = 1)
	tastes = list("d'hypocrisie" = 1)
	bait_quality = GREAT_QUALITY_BAIT_TRAIT

/obj/item/food/bait/doughball
	name = "Boule de pâte"
	desc = "Un petit morceau de pâte. Simple, mais fait un appât correct."
	icon = 'icons/obj/fishing.dmi'
	icon_state = "doughball"
	food_reagents = list(/datum/reagent/consumable/nutriment/protein = 1)
	tastes = list("de pâte" = 1)
	foodtypes = GRAIN
	w_class = WEIGHT_CLASS_TINY
	bait_quality = BASIC_QUALITY_BAIT_TRAIT
	rod_overlay_icon_state = "dough_overlay"

/// These are generated by tech fishing rod
/obj/item/food/bait/doughball/synthetic
	name = "synthetic doughball"
	icon_state = "doughball"
	preserved_food = TRUE
